/** Every page in the sitemap (docs/SPEC.md), with fixtures standing in for missing content. */
export const PAGES = {
  home: '/',
  plantings: '/plantings',
  'planting-upcoming': '/plantings/example-upcoming',
  'planting-held': '/plantings/silukhanyo-primary-2026-08-29',
  'get-involved': '/get-involved',
  'dedicate-a-tree': '/dedicate-a-tree',
  donate: '/donate',
  'propose-a-site': '/get-involved/propose-a-site',
  partner: '/get-involved/partner',
  'our-work': '/our-work',
  'site-silukhanyo': '/sites/silukhanyo-primary',
  'site-mhani-gingi': '/sites/mhani-gingi-centre-of-excellence',
  'site-genadendal': '/sites/genadendal',
  about: '/about',
  journal: '/journal',
  'journal-post': '/journal/example-post',
  privacy: '/privacy',
  'thank-you': '/thank-you/planting',
} as const;
